name: Python Lambda Application Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      # Removido o bloco de testes com pytest, já que estava comentado
      # - name: Test with pytest
      #   run: |
      #     pytest    

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Build Docker image
        run: |
          docker build -t hello_world_repository:${{ github.run_id }} application/

      - name: Login to AWS ECR
        env:
          AWS_REGION: us-east-1
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 654654632496.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Tag and Push Docker image to ECR
        run: |
          docker tag hello_world_repository:${{ github.run_id }} 654654632496.dkr.ecr.${{ env.AWS_REGION }}/hello_world_repository:${{ github.run_id }}          
          docker push 654654632496.dkr.ecr.${{ env.AWS_REGION }}/hello_world_repository:${{ github.run_id }}

      - name: Set Docker image URL as output
        run: |
          echo "image=654654632496.dkr.ecr.${{ env.AWS_REGION }}/hello_world_repository:${{ github.run_id }}" >> $GITHUB_OUTPUT
